[repository]
default_branch = 'master'
enable_commit = true
enable_tag = false

[[transforms]]
path = 'Formula/kotlin-tix.rb'
replace = ':tag => "{version}"'

[[transforms]]
path = 'Formula/tix.rb'
replace = ':tag => "{version}"'
